# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "netem" do |netem|

    netem.vm.network "private_network", ip: "192.167.101.12"
    netem.vm.network "private_network", ip: "192.167.100.12"

    netem.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    netem.vm.provision :shell, path: "setup_netem.sh"
    netem.vm.provision "file", source: "start_experiments.sh", destination: "$HOME/start_experiments.sh"
    netem.vm.provision "file", source: "network_trace1", destination: "$HOME/network_trace1"
    netem.vm.provision "file", source: "network_trace2", destination: "$HOME/network_trace2"
    netem.vm.provision "file", source: "network_trace0", destination: "$HOME/network_trace0"
  end

  config.vm.define "client1", primary: true do |client1|

    client1.vm.network "private_network", ip: "192.167.100.11"

    client1.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
      config.ssh.forward_agent = true
    end

    client1.vm.provision :shell, path: "setup_client.sh"
    client1.vm.provision "file", source: "start_streaming.sh", destination: "$HOME/start_streaming.sh"
	config.vm.synced_folder "../DASH-Setup/client", "/home/vagrant/DASH-setup"

  end

  config.vm.define "server1" do |server1|

    server1.vm.network "private_network", ip: "192.167.101.13"
    server1.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    server1.vm.provision :shell, path: "setup_server.sh"
	config.vm.provision "file", source: "../DASH-setup/server/public/video", destination: "$HOME/video-content"
    config.vm.synced_folder "../DASH-setup/server", "/home/vagrant/DASH-setup"
  end

end
