# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "netem" do |netem|

    netem.vm.network "private_network", ip: "192.167.101.12"
    netem.vm.network "private_network", ip: "192.167.100.12"

    netem.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    netem.vm.provision :shell, path: "setup_netem.sh"
    netem.vm.provision :shell, path: "startup_netem.sh", run: "always"

	  netem.vm.provision "file", source: "netem_start_trace.sh", destination: "$HOME/netem_start_trace.sh"
	  netem.vm.provision "file", source: "trace_killer.sh", destination: "$HOME/trace_killer.sh"
	  netem.vm.provision "file", source: "trace_files", destination: "trace_files"
  end

  config.vm.define "client", primary: true do |client|

    client.vm.network "private_network", ip: "192.167.100.11"

    client.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
      config.ssh.forward_agent = true
    end

    client.vm.provision :shell, path: "setup_client.sh"
    client.vm.provision :shell, path: "startup_client.sh", run: "always"
	  
    client.vm.synced_folder "../DASH-setup/client", "/home/vagrant/DASH-setup"

  end

  config.vm.define "server" do |server|

    server.vm.network "private_network", ip: "192.167.101.13"
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    server.vm.provision :shell, path: "setup_server.sh"
    server.vm.provision :shell, path: "startup_server.sh", run: "always"
  	server.vm.provision "file", source: "../DASH-setup/server/public/videos", destination: "$HOME/video-content"
  
    server.vm.synced_folder "../DASH-setup/server", "/home/vagrant/DASH-setup"
  end

end
